# Good Missions

[[missions]]
name = "Last Minute"
description = "Drink only during the 3rd lap of each race."

[[missions]]
name = "Pacing"
description = "*Must* have 5 gulps per race excluding last race."

[[missions]]
name = "Smuggler"
description = "Finish *one* race holding or using a powerful item."
details = ["Applicable items: Star, lightning, bullet bill, blue shell, golden mushroom, endless 8."]
200cc_adjustment = "During a 6 race Gran Prix, complete the mission twice."

[[missions]]
name = "Janitor"
description = "Clean up a number of stationary non-coin items equal to 2 times the number of races."
200cc_adjustment = "The amount to clean up is equal to the number of races."

[[missions]]
name = "Forgot my Keys"
description = "On each race, Starting after the drink line, you must touch twelfth place."
200cc_adjustment = "During a 6 race Gran Prix, you must follow the rule in only 4 of those races."

[[missions]]
name = "Showboating"
description = "Can only start drinking in 1st place."
details = ["You can keep drinking even if you leave 1st place."]

[[missions]]
name = "Randomizer"
description = "Use this random loadout:"
needs_random_loadout = true

[[missions]]
name = "Sheep"
description = "Can only start a drink after someone else puts down their drink."

[[missions]]
name = "Item Masher"
description = "Hold every item for less than 2 seconds before using it."

[[missions]]
name = "Locked Out"
description = "In only *half* of the races, you can't use your first item."

[[missions]]
name = "One in the Chamber"
description = "Can't use any bullet bills."
details = ["Lose them through getting shocked or ghosted."]

[[missions]]
name = "Stockpile"
description = "Must always have a second item on hold before you hold or use an item."
details = ["You can not use your item before picking up a double."]

[[missions]]
name = "Picky Drinker"
description = "You can only drink while holding this random item:"
needs_random_item = true

[[missions]]
name = "TheOddOne"
description = "Start drinking in an odd numbered place, stop drinking in an odd numbered place."
details = ["You're playing with fire if you are pushing on 11th."]

[[missions]]
name = "Pay to Win"
description = "Drink while only at 10 coins."

[[missions]]
name = "Designated Driver"
description = "Can only drink while Lakitu is carrying you."

[[missions]]
name = "Tavern Brawler"
description = "This random race number is the only race you can drink your entire beer:"
needs_random_number = 4

[[missions]]
name = "Masochist"
description = "Designate a player at the start. Get hit by that player twice."
details = ["Running into their hazardous behind counts."]

[[missions]]
name = "Gary Oak"
description = "The first player who pisses you off during the Gran Prix is your rival. You must hit them 3 times."

# Niche Missions

[[missions]]
name = "Collateral Damage"
description = "Get hit by a blue shell while it isn’t locked onto you, *or* get hit by a bullet bill."

[[missions]]
name = "Secret Santa"
description = "Bestow 3 positive effects to others with any rotating item around you."
details = ["This is a hard to see visual effect - the item isn't consumed."]

[[missions]]
name = "Pack Rat"
description = "If you get 6th or 7th place in the Grand Prix, you win alongside the next best player."
details = ["Deep inside, you didn't win."]

[[missions]]
name = "No One's Main"
description = "Race using an inside-drifting bike."

[[missions]]
name = "Bumper Cars"
description = "Must bump every player without any attacks from either side."

[[missions]]
name = "The Mark"
description = "Mark-drift over 2 coin collections."
details = ["Mark-drift: Pick up all coins (at least 3) from a string of coins designed to be picked up with proper steering/drifting."]

[[missions]]
name = "Sticky Keys"
description = "Turn on auto accelerate. Your controller must be fully put down before drinking."

[[missions]]
name = "Watch Your Back"
description = "While in first, you must toggle rear view camera at least every 2 seconds."

[[missions]]
name = "Double or Nothing"
description = "You can not pick up single item containers."
details = ["You can waive a single race. Save this for any mistakes."]
200cc_adjustment = "During a 6 race Gran Prix, you waive two races instead."

[[missions]]
name = "Drowning in Sorrow"
description = "You can only drink while submerged in water."

# Coop Missions

[[coopmissions]]
all_items = true 
