[[rules]]
name = "Last Minute"
description = "Drink only during the 3rd lap of each race."

[[rules]]
name = "Pacing"
description = "Must have 5 gulps per race excluding last race."

[[rules]]
name = "Smuggler"
description = "Finish one race holding or using a powerful item. Bullet bill, star, lightning, blue shell, golden mushroom, endless 8"

[[rules]]
name = "Janitor"
description = "Clean up a number of stationary non-coin items equal to 2 times the number of races."

[[rules]]
name = "Forgot my Keys"
description = "On each race, Starting after the drink line, you must touch twelfth place."

[[rules]]
name = "Showboating"
description = "Can only start drinking in 1st place."

[[rules]]
name = "Randomizer"
description = "Random character, kart, and wheel selection."

[[rules]]
name = "Sheep"
description = "Can only start a drink after someone else drinks."

[[rules]]
name = "Item Masher"
description = "Hold every item for less than 2 seconds. Hold the break for 1 second if you slip up."

[[rules]]
name = "Locked Out"
description = "In only half of the races, you can’t use your first item."

[[rules]]
name = "One in the Chamber"
description = "Can’t use any bullet bills."

[[rules]]
name = "Stockpile"
description = "Must always have a second item on hold before you hold or use an item. You can not use your item before picking up a double."

[[rules]]
name = "Picky Drinker"
description = "You can only drink while you are holding this randomly selected item"

[[rules]]
name = "Odd Man Out"
description = "Start drinking in an odd place, stop drinking in an odd place. You’re playing with fire if you are pushing on 11th."
