name: Deploy Leptos to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write # for committing to gh-pages branch.
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Rust stable
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      # Explicitly add WASM target
      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      # Cache cargo dependencies
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install wasm-bindgen-cli
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --locked

      # Build the project
      - name: Build project
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-dir ./dist --target web ./target/wasm32-unknown-unknown/release/beerio.wasm
          cp -r assets/* out/ 2>/dev/null || :  # Silently fail if no assets

     # Deploy with Github Static Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
          # token:
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist dir
          path: './dist'
    
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
