name: Deploy Leptos to GitHub Pages

on:
  push:
    branches: [main]  # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Rust (stable) and wasm target
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown

      # Cache cargo dependencies to speed up builds
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install wasm-bindgen-cli
      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli --locked

      # Build the project (client-side only for GitHub Pages)
      - name: Build project
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-dir ./out --target web ./target/wasm32-unknown-unknown/release/YOUR_CRATE_NAME.wasm
          cp -r assets/* out/  # If you have static assets

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: false  # Clean the directory before deployment
